/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete_Jugueteria;

import static Paquete_Jugueteria.Recibo.lista;
import static Paquete_Jugueteria.Recibo.total_compra;
import static Paquete_Jugueteria.Recibo.total_juguetes;
import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Programación
 */
public class Panel_Jug extends javax.swing.JFrame {
    conexion enlace = new conexion();
    Connection connect = enlace.conectar();
    
    DefaultTableModel lista = new DefaultTableModel();
    
    public Panel_Jug() {
        
        initComponents();
        lista.addColumn("Juguete");
        lista.addColumn("Cantidad");
        lista.addColumn("Precio Unitario");
        lista.addColumn("Precio Total");
        
        this.lista_de_juguetes.setModel(lista);
        this.setLocationRelativeTo(null);
        
        precio_tot_x_jug.setEditable(false);
        fecha_compra.setText(FechaActual());
        fecha_compra.setEditable(false);
        editar.setEnabled(false);
    }
    
    public void probar_con(){
        if (connect == null) {
            JOptionPane.showMessageDialog(null, "Conexión Fallida");
        } else {
            JOptionPane.showMessageDialog(null, "Conexión Exitosa");
        }
    }
    
    public static String FechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formato_fecha = new SimpleDateFormat("dd/MM/YYYY");
        return formato_fecha.format(fecha);
    }
    
    public void Agregar() {
        Object Compra_Juguetes [] = new Object [4];
        Compra_Juguetes[0] = menu_jug.getSelectedItem();
        Compra_Juguetes[1] = cant_jug.getText();
        Compra_Juguetes[2] = precio_jug.getText();
        Compra_Juguetes[3] = precio_tot_x_jug.getText();
        
        lista.addRow(Compra_Juguetes);
    }
    
    public void Limpiar(){
        menu_jug.setSelectedItem(null);
        precio_jug.setText("");
        cant_jug.setText("");
        precio_tot_x_jug.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        id_cliente = new javax.swing.JTextField();
        nombre_cliente = new javax.swing.JTextField();
        etiq_id = new javax.swing.JLabel();
        etiq_cliente = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        panel_info_compra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menu_jug = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fecha_compra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cant_jug = new javax.swing.JTextField();
        boton_limpiar = new javax.swing.JButton();
        boton_agregar = new javax.swing.JButton();
        precio_tot_x_jug = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        precio_jug = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        calc_precio_tot = new javax.swing.JButton();
        prec_unitario = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_de_juguetes = new javax.swing.JTable();
        etiq_lista = new javax.swing.JLabel();
        boton_eliminar = new javax.swing.JButton();
        recibo_boton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        compra_total = new javax.swing.JButton();
        total_compra = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, 50));

        nombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 210, 50));

        etiq_id.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        etiq_id.setForeground(new java.awt.Color(255, 255, 255));
        etiq_id.setText("Cédula:");
        jPanel1.add(etiq_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        etiq_cliente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        etiq_cliente.setForeground(new java.awt.Color(255, 255, 255));
        etiq_cliente.setText("Cliente:");
        jPanel1.add(etiq_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("JUGUETERÍA COPILUL");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 14, 940, 70));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        logo.setText("jLabel1");
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 100));

        panel_info_compra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_info_compra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Información de la Compra");
        panel_info_compra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 367, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad:");
        panel_info_compra.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        menu_jug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Muñeca", "Carro", "Casa de Muñecas", "Pista de Carros", "Balón de Vóleibol", "Balón de Fútbol", "Balón de Baloncesto", "Ajedrez", "Parqués", "UNO", "Dominó", "Oso de Felpa", "Sonajero" }));
        panel_info_compra.add(menu_jug, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 133, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de la Compra:");
        panel_info_compra.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 77, -1, -1));
        panel_info_compra.add(fecha_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 77, 133, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Precio Total:");
        panel_info_compra.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        cant_jug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant_jugActionPerformed(evt);
            }
        });
        panel_info_compra.add(cant_jug, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 133, -1));

        boton_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar_bot.png"))); // NOI18N
        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });
        panel_info_compra.add(boton_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 110, -1));

        boton_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir_bot.png"))); // NOI18N
        boton_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_agregarActionPerformed(evt);
            }
        });
        panel_info_compra.add(boton_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 47, -1));
        panel_info_compra.add(precio_tot_x_jug, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 133, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precio Unitario:");
        panel_info_compra.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        precio_jug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_jugActionPerformed(evt);
            }
        });
        panel_info_compra.add(precio_jug, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 133, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Juguete:");
        panel_info_compra.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        calc_precio_tot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio_total.png"))); // NOI18N
        calc_precio_tot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_precio_totActionPerformed(evt);
            }
        });
        panel_info_compra.add(calc_precio_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 40, -1));

        prec_unitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/precio jug.png"))); // NOI18N
        prec_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prec_unitarioActionPerformed(evt);
            }
        });
        panel_info_compra.add(prec_unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 40, -1));

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar bot.png"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        panel_info_compra.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 100, 40));

        jPanel1.add(panel_info_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 400, 360));

        lista_de_juguetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(lista_de_juguetes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, 159));

        etiq_lista.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etiq_lista.setForeground(new java.awt.Color(255, 255, 255));
        etiq_lista.setText("Lista de Juguetes a Comprar");
        jPanel1.add(etiq_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        boton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar bot.png"))); // NOI18N
        boton_eliminar.setText("  Eliminar");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 130, 50));

        recibo_boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/recibo.png"))); // NOI18N
        recibo_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibo_botonActionPerformed(evt);
            }
        });
        jPanel1.add(recibo_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 130, 150));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Generar Recibo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 650, 130, -1));

        compra_total.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/total_compra.png"))); // NOI18N
        compra_total.setText("Total Compra");
        compra_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compra_totalActionPerformed(evt);
            }
        });
        jPanel1.add(compra_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 170, 50));

        total_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_compraActionPerformed(evt);
            }
        });
        jPanel1.add(total_compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, 170, 50));

        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ver.png"))); // NOI18N
        actualizar.setText("  Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        jPanel1.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 130, 50));

        guardar.setText("guardar BD");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1109, 776));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_clienteActionPerformed

    private void nombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_clienteActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_boton_limpiarActionPerformed

    private void boton_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_agregarActionPerformed
        try {
            Agregar();
            Limpiar();
        } catch(Exception exc) {
            JOptionPane.showMessageDialog(null, "Digite Información antes de Agregar");
        }
    }//GEN-LAST:event_boton_agregarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        try {
            int rta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar la fila?");
            if (rta == 0) {
                int pos = lista_de_juguetes.getSelectedRow();
                lista.removeRow(pos);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila para poder eliminarla");
        }
    }//GEN-LAST:event_boton_eliminarActionPerformed

    private void compra_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compra_totalActionPerformed
        double compra, acumulado = 0;
        int tot_filas = lista.getRowCount();
        for (int i = 0; i < tot_filas; i++) {
            compra = Double.parseDouble(String.valueOf(lista.getValueAt(i, 3)));
            acumulado = acumulado + compra;
        }
        total_compra.setText(String.valueOf(acumulado));
    }//GEN-LAST:event_compra_totalActionPerformed

    private void recibo_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibo_botonActionPerformed


        Recibo rbo = new Recibo();
        rbo.setVisible(true);
        
        Recibo.nombre_cliente.setText(nombre_cliente.getText());
        Recibo.cedula_cliente.setText(id_cliente.getText());
        Recibo.fecha_compra.setText(fecha_compra.getText());
        Recibo.total_compra.setText(total_compra.getText());
        
        int cants, acumulado = 0;
        int tot_filas = lista.getRowCount();
                for (int i = 0; i < tot_filas; i++) {
                    cants = Integer.parseInt(String.valueOf(lista.getValueAt(i, 1)));
                    acumulado += cants;
                }
        Recibo.total_juguetes.setText(String.valueOf(acumulado));
        
        
        double total_comp, iva;
        total_comp = Double.parseDouble(total_compra.getText());
        iva = total_comp * 0.19;    
        Recibo.IVA.setText(String.valueOf(iva));
        
        double comp_mas_iva;
        comp_mas_iva = total_comp + iva;
        Recibo.total_mas_iva.setText(String.valueOf(comp_mas_iva));
        
        
        
        for (int i = 0; i < lista.getRowCount(); i++) {
            String tbl[] = new String[4];
            tbl[0] = lista_de_juguetes.getValueAt(i, 0).toString();
            tbl[1] = lista_de_juguetes.getValueAt(i, 1).toString();
            tbl[2] = lista_de_juguetes.getValueAt(i, 2).toString();
            tbl[3] = lista_de_juguetes.getValueAt(i, 3).toString();
            Recibo.lista.addRow(tbl);
        }
        
        /*
        lista.addRow(Recibo.juguetes_comprados);
        */
    }//GEN-LAST:event_recibo_botonActionPerformed

    private void cant_jugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant_jugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant_jugActionPerformed

    private void precio_jugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_jugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_jugActionPerformed

    private void calc_precio_totActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_precio_totActionPerformed
        double precio_unitario, cant_art, total;
        precio_unitario = Double.parseDouble(precio_jug.getText());
        cant_art = Double.parseDouble(cant_jug.getText());
        
        total = precio_unitario * cant_art;
        precio_tot_x_jug.setText(String.valueOf(total));
    }//GEN-LAST:event_calc_precio_totActionPerformed

    private void total_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_compraActionPerformed

    private void prec_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prec_unitarioActionPerformed
        if (menu_jug.getSelectedItem().equals("UNO")) {
            precio_jug.setText("18000");
        } else if (menu_jug.getSelectedItem().equals("Muñeca")) {
            precio_jug.setText("24500");
        } else if (menu_jug.getSelectedItem().equals("Carro")) {
            precio_jug.setText("15000");
        } else if (menu_jug.getSelectedItem().equals("Casa de Muñecas")) {
            precio_jug.setText("100000");
        } else if (menu_jug.getSelectedItem().equals("Pista de Carros")) {
            precio_jug.setText("92000");
        } else if (menu_jug.getSelectedItem().equals("UNO")) {
            precio_jug.setText("18000");
        } else if (menu_jug.getSelectedItem().equals("Balón de Vóleibol")) {
            precio_jug.setText("41000");
        } else if (menu_jug.getSelectedItem().equals("Balón de Fútbol")) {
            precio_jug.setText("55000");
        } else if (menu_jug.getSelectedItem().equals("Balón de Baloncesto")) {
            precio_jug.setText("68000");
        } else if (menu_jug.getSelectedItem().equals("Ajedrez")) {
            precio_jug.setText("80000");
        } else if (menu_jug.getSelectedItem().equals("Parqués")) {
            precio_jug.setText("25000");
        } else if (menu_jug.getSelectedItem().equals("Dominó")) {
            precio_jug.setText("62000");
        } else if (menu_jug.getSelectedItem().equals("Oso de Felpa")) {
            precio_jug.setText("43000");
        } else if (menu_jug.getSelectedItem().equals("Sonajero")) {
            precio_jug.setText("11500");
        }
    }//GEN-LAST:event_prec_unitarioActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try{    
            int fs = lista_de_juguetes.getSelectedRow();
            int rta = JOptionPane.showConfirmDialog(null, "¿Desea ejecutar la actualización?");
            if (rta == 0) {
                lista.setValueAt(menu_jug.getSelectedItem(), fs, 0);
                lista.setValueAt(cant_jug.getText(), fs, 1);
                lista.setValueAt(precio_jug.getText(), fs, 2);
                lista.setValueAt(precio_tot_x_jug.getText(), fs, 3);
                
                editar.setEnabled(false);
                boton_agregar.setEnabled(true);
                Limpiar();
            }
        } catch(Exception e){
            JOptionPane.showInputDialog("Debe llenar todos los campos");
        }
    }//GEN-LAST:event_editarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try{
            int fila_selc = lista_de_juguetes.getSelectedRow();
            String jugs = (String) (lista.getValueAt(fila_selc, 0));
            menu_jug.setSelectedItem(jugs);
            cant_jug.setText(lista.getValueAt(fila_selc, 1).toString());
            precio_jug.setText("0");
            precio_tot_x_jug.setText("0");
            
            precio_tot_x_jug.setEditable(false);
            precio_jug.setEditable(false);
            editar.setEnabled(true);
            boton_agregar.setEnabled(false);
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Debe elegir una fila");
        }
    }//GEN-LAST:event_actualizarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            PreparedStatement pps = connect.prepareStatement("INSERT INTO venta (cliente, cedula, fecha_compra, juguete, cant_juguete, precio_un_jug, precio_tot_jug, total_compra) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            pps.setString(1, nombre_cliente.getText());
            pps.setInt(2, Integer.parseInt(id_cliente.getText()));
            pps.setString(3, fecha_compra.getText());
            pps.setString(4, (menu_jug.getSelectedItem()).toString());
            pps.setInt(5, Integer.parseInt(cant_jug.getText()));
            pps.setInt(6, Integer.parseInt(precio_jug.getText()));
            
            pps.setDouble(7, Double.parseDouble(precio_tot_x_jug.getText()));
            pps.setDouble(8, Double.parseDouble(total_compra.getText()));
            
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos Guardados");
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Jug.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Jug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Jug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Jug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Jug.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Jug().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton boton_agregar;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JButton calc_precio_tot;
    private javax.swing.JTextField cant_jug;
    private javax.swing.JButton compra_total;
    private javax.swing.JButton editar;
    private javax.swing.JLabel etiq_cliente;
    private javax.swing.JLabel etiq_id;
    private javax.swing.JLabel etiq_lista;
    public static javax.swing.JTextField fecha_compra;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton guardar;
    public static javax.swing.JTextField id_cliente;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable lista_de_juguetes;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> menu_jug;
    public static javax.swing.JTextField nombre_cliente;
    private javax.swing.JPanel panel_info_compra;
    private javax.swing.JButton prec_unitario;
    private javax.swing.JTextField precio_jug;
    private javax.swing.JTextField precio_tot_x_jug;
    private javax.swing.JButton recibo_boton;
    private javax.swing.JLabel titulo;
    public static javax.swing.JTextField total_compra;
    // End of variables declaration//GEN-END:variables
}
